### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by kragit** [riasvdv/craft-position-fieldtype#10]
The documentation link on the Plugin Settings page is broken. It links to: `https://github.com/Rias500/position-fieldtype/blob/master/README.md` which results in a 404.

The Plugin Store documentation link is good and correctly links to `https://github.com/Rias500/craft-position-fieldtype/blob/master/README.md`

**Comment by riasvdv** [comment]
Thanks for reporting this! I fixed it yesterday but the documentation links get cached locally which is why you're seeing the old url in your control panel, the fastest way to fix this is to re-install the plugin.
