### ISSUE TITLE
Responsive Buttons

### ISSUE THREAD

**Issue by kragit** [riasvdv/craft-position-fieldtype#11]
If using the Position fieldtype within something like SuperTable in it's 'static table' configuration, the buttons can extend beyond their container and cover other fields.

If possible, it would be great if the buttons could 'wrap' themselves when constrained in such a way.

Current:
![screen shot 2018-04-04 at 8 28 05 pm](https://user-images.githubusercontent.com/296050/38341474-b9d6779e-3846-11e8-8514-398948362ec5.png)

Possible fixed behavior:
![positionalternate](https://user-images.githubusercontent.com/296050/38341735-0c6afa6a-3848-11e8-8f9c-0eb59558f159.jpg)

**Comment by riasvdv** [comment]
Fixed in 1.0.13!
