### ISSUE TITLE
Position options not showing 

### ISSUE THREAD

**Issue by alanski66** [riasvdv/craft-position-fieldtype#15]
Using in a matrix block on home page and just as a normal field i cant see any position.
Position_input.twig - if i remove the logic check around output all seems to work ok.
   {% if field.options[option] %}
            <div title="{{ label }}" class="btn big {% if value is not null ? option == value : field.default == option %} active{% endif %} position-icon-{{ option }}" data-option="{{ option }}"></div>
        {% endif %}

So  field.options[option] is returning nothing - is this redundant?

**Comment by riasvdv** [comment]
Are you still having this issue? I'm having trouble reproducing it. Please reopen if it's still happening.

**Comment by alanski66** [comment]
Having this issue when position field is in a matrix. The icons do not show
