### ISSUE TITLE
No icons in matrix block

### ISSUE THREAD

**Issue by alanski66** [riasvdv/craft-position-fieldtype#18]
WHen using a matrix block and position fieldtype is part of the block, I can't see any icons. There are no js errors. Looks like the ico-fonts are not loading or even there:
![position-field](https://user-images.githubusercontent.com/1781739/48136908-c1417900-e298-11e8-82f0-d613cb41391f.jpg)

**Comment by riasvdv** [comment]
This works on all my sites and I haven't had anyone else with this issue. Are you still experiencing this? Closing for now.
