### ISSUE TITLE
Twig Runtime Error

### ISSUE THREAD

**Issue by br-designer** [riasvdv/craft-position-fieldtype#2]
Getting a Twig Runtime Error when creating / editing fields. 

<img width="2390" alt="screen shot 2017-12-06 at 4 00 22 pm" src="https://user-images.githubusercontent.com/5600724/33687757-be851530-da9e-11e7-8e4b-b6a90dd83f0c.png">

**Comment by edolyne** [comment]
@br-designer PR #1 will solve this issue.

**Comment by riasvdv** [comment]
Fix in 1.0.2!
