### ISSUE TITLE
fail to instantiate component after dump-autoload

### ISSUE THREAD

**Issue by pieterjandebruyne** [riasvdv/craft-position-fieldtype#20]
Running 
```
composer dump-autoload -a
```
gives problems initiating the PositionFieldtypeAsset.. when i try to acces the CP /craft/settings/fields/new
running 
```
composer install
```
fixes the issue..

Not sure if there is something you can do about this.

Screenshot error: https://ibb.co/rM5mKxc
Pastebin of error: https://pastebin.com/?__cf_chl_jschl_tk__=3471c03aa50d5fe665b67cf1e3d3b5b41397bd99-1576233104-0-AR3_4GzEkeCdZlac2uH5rvTpU0hgCSXYGKP_qdOlD5HxS_gqohFjyIkmIc-Jw6_Zhoavrt9IN_OvshlGuMd1WwgtqZBMEIqBvIETEtaYVa6Rf02mBQbeBfd_NFJ13xpYcj9J4-lTY0QVNCxo6iiVh_Aprm81iRPuTigjRS9aQ6Yyj_KqBKsITG1gmujsJwIPqSeg215yygSZIoUpnhpv7E6tikJ-jK6M--mnu3g5LmZGu8lL2ZZMSlDx7iMHYLa-3x30d5dEEWasBBL-rJXLWnA

**Comment by jan-dh** [comment]
Had same issue today:

```
Failed to instantiate component or class "rias\positionfieldtype\assetbundles\positionfieldtype\PositionFieldtypeAsset".
↵
Caused by: ReflectionException
Class rias\positionfieldtype\assetbundles\positionfieldtype\PositionFieldtypeAsset does not exist
```

Had to remove my vendor folder and do a fresh composer install.

**Comment by TomDeSmet** [comment]
We have this issue all the time lately.
Doing ```composer update``` fixes it.
But it should be looked at, because it's very annoying, especially when it only shows up after a production deploy!

**Comment by DynamiteGoesBoom** [comment]
is this still an issue for you guys?

**Comment by DynamiteGoesBoom** [comment]
Closing due to age and lack of info.
