### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by Antimated** [riasvdv/craft-position-fieldtype#24]
Are there any plans to have support for craft 4? Couldn't find the plugin on the plugin store on a Craft CMS 4.0.0-beta.1 install :(

**Comment by DynamiteGoesBoom** [comment]
Yeah we should have some time next month to begin getting into porting our plugins over to 4.

**Comment by janhenckens** [comment]
Hey @DynamiteGoesBoom, any updates on this? I have the plugin working on Craft 4 in a fork, happy to make a PR for it if you'd like to use that.

**Comment by DynamiteGoesBoom** [comment]
Hey @janhenckens thanks for the offer and if you would like to send us a PR. We can certainly test it out on our end. 

Thanks again!

**Comment by janhenckens** [comment]
Here's the PR: https://github.com/hybridinteractive/craft-position-fieldtype/pull/25

**Comment by DynamiteGoesBoom** [comment]
Thanks @janhenckens this has been tested, released, and is published on the plugin store.

**Comment by jordikroon** [comment]
Hi there,

Thanks for the work on the Craft 4 release. Any news on when this plugin is expected to be out of beta?

**Comment by janhenckens** [comment]
Can we get this tagged as a stable release please? @DynamiteGoesBoom

**Comment by DynamiteGoesBoom** [comment]
This is on our list, we'll get to it as soon as we can.
